Databases week2
shravanipagilla/hyf-homework pull request #23
Opened 2022-08-25 18:42 UTC by shravanipagilla

finished databases_week2 homework...

2022-08-26 10:29 UTC, ReenuMary reviewed
Good job Shravani!!

2022-08-26 10:29 UTC, ReenuMary commented on databases/week2/school_database.sql
> +CREATE INDEX name ON Student (name);
it will be a good practice to name indexes with prefix idx_ , just like we use fk_ for foreign keys.

2022-08-26 10:29 UTC, ReenuMary commented on databases/week2/More_queries_lesson2.sql
> + select month(created) AS Month , count(*)
month name(created) will give you the name of the month, if you want ..

2022-08-26 10:29 UTC, ReenuMary commented on databases/week2/More_queries_lesson2.sql
> +where user.name= 'Maryrose Meadows' AND  month(created)=10;
for September month(created)=9

2022-08-26 10:29 UTC, ReenuMary commented on databases/week2/More_queries_lesson2.sql
> +select *
just a suggestion , you can also specify the relevant columns you want to display and use alias names for better readability

2022-08-26 10:29 UTC, ReenuMary commented on databases/week2/More_queries_lesson2.sql
> + select *
a suggestion , it will look better if you are consistent with the usage of upper case on the keywords

2022-09-04 10:27 UTC, Elia-Git requested changes
Pls implement feedback from ReenuMary. Thx.

2022-09-05 20:56 UTC, shravanipagilla commented
Thank you for comments on my code, i made changes as per comments thank you @Elia-Git , @ReenuMary .  :)

2022-09-05 20:56 UTC, merged