finished databases_week3 homework.
shravanipagilla/hyf-homework pull request #24
Opened 2022-09-01 18:49 UTC by shravanipagilla

2022-09-04 21:56 UTC, Elia-Git requested changes
Pls consider to implement given feedback-

2022-09-04 21:56 UTC, Elia-Git commented on databases/week3/create_queries.sql
> +GROUP BY Meal.id;
I would modify this as below instead.
```
SELECT
    Meal.title,
    Meal.max_reservations, sum(Reservation.number_of_guests) AS booked spots
FROM Meal
    JOIN Reservation ON meal.id = Reservation.meal_id
GROUP BY Reservation.meal_id
HAVING Meal.max_reservations> booked spots;
```

2022-09-04 21:56 UTC, Elia-Git commented on databases/week3/create_queries.sql
> +ORDER BY `Reservation`.`created_date`;*/
Don't commit commented or empty lines of code!

2022-09-04 21:56 UTC, Elia-Git commented on databases/week3/create_queries.sql
> +WHERE Review.description = 'good';
Here all meal descriptions might not have qualitative description. Instead we should classify meals into bad, moderate or good as per the nr reviews (stars given).
Try like this..
```
SELECT Meal.*,review.stars AS Stars_recieved FROM Meal
JOIN Review ON meal.id=Review.meal_Id
WHERE Review.stars>20;
```

2022-09-04 21:56 UTC, Elia-Git commented on databases/week3/create_queries.sql
> +ORDER BY `Reservation`.`created_date`;
Why parenthesis around `Reservation.created_date` ...? make sure if the query can run with parenthesis. 
Pls try like this
```
SELECT Meal.title,Meal.price
FROM Meal
    INNER JOIN Reservation ON Reservation.meal_id = Meal.id
WHERE Meal_id = 2
ORDER BY Reservation.created_date ASC;
```

2022-09-04 21:56 UTC, Elia-Git commented on databases/week3/create_queries.sql
> +ORDER BY AVG(Review.stars);
Good here.

2022-09-04 21:56 UTC, Elia-Git commented on databases/week3/create_queries.sql
> +                           -- Reservation queries..
Remove empty lines,not a good practice

2022-09-05 19:44 UTC, shravanipagilla commented
@Elia-Git  Thank you very much for your comments and review. I resolved all the comments.

2022-09-05 19:44 UTC, merged