react1-week2 homework
shravanipagilla/hyf-homework pull request #30
Opened 2022-10-08 11:07 UTC by shravanipagilla

2022-10-12 15:31 UTC, annamourasobral requested changes
Hey, @shravanipagilla 
Really nice code, with a lot of high-order functions, props, and ternary operators, you are working with real-life developers' tools! 
I suggested some adjustments to get it even better, I hope you find it useful. 
Happy coding! 👩🏻‍💻

2022-10-12 15:31 UTC, annamourasobral commented on react/week2/my-react-app/src/App.js
> +const arrayOfTodos = [
you can store this data in another file

2022-10-12 15:31 UTC, annamourasobral commented on react/week2/my-react-app/src/App.js
> +      console.log(id)
clean you console.logs

2022-10-12 15:31 UTC, annamourasobral commented on react/week2/my-react-app/src/App.js
> +      const id = Math.floor(Math.random() * (100 - 4 + 1)) + 4;
smart way of making a unique id! 😉

2022-10-12 15:31 UTC, annamourasobral commented on react/week2/my-react-app/src/App.js
> +    console.log("delete", id)
clean up console.logs

2022-10-12 15:31 UTC, annamourasobral commented on react/week2/my-react-app/src/Todos/AddTodo.jsx
> +            <button onClick={onClick}>{visible ? "Submit" : "Add new Todo"}</button>
submit has to work with Enter key

2022-10-12 15:31 UTC, annamourasobral commented on react/week2/my-react-app/src/App.js
> +  const addTodo = (description) => {
you have a function and a component called addTodo, it's confusing

2022-10-12 15:31 UTC, annamourasobral commented on react/week2/my-react-app/src/App.js
> +import Todos from './Todos/Todos';
the components folder is usually called components

2022-10-12 15:31 UTC, annamourasobral commented on react/week2/my-react-app/src/Todos/Todos.jsx
> +const TodoItem = ({ id, description, onDelete }) => {
this should be another component

2022-10-12 15:31 UTC, annamourasobral commented on react/week2/my-react-app/src/Todos/AddTodo.jsx
> +const AddTodo = ({ onAdd }) => {
this whole code should be in TodoItem component

2022-10-12 15:31 UTC, annamourasobral commented on react/week2/my-react-app/src/Todos/Todos.jsx
> +                    <TodoItem id={todo.id} description={todo.description} onDelete={onDelete} />
id and description should be accessed only on TodoItem

2022-10-12 15:31 UTC, annamourasobral commented on react/week2/my-react-app/src/App.js
> +      setTodos(todos.concat({
if you are using setTodos to add a new item you can simply destructure the array and add the new todo 
```suggestion
      setTodos(...todos, {
```

2022-10-15 08:39 UTC, shravanipagilla commented on react/week2/my-react-app/src/App.js
> +      const id = Math.floor(Math.random() * (100 - 4 + 1)) + 4;
thank you :)

2022-10-15 10:54 UTC, annamourasobral commented
Hey, @shravanipagilla 
I saw that you delivered PR #31 with the same suggestions that I commented on here. I greatly recommend you address them before going forward next time.
It spares you from doing the same adjustments in two different PR and the Mentors from reviewing the same code.
If you have any questions about the review don't hesitate to contact me! ☺️

2022-10-15 23:21 UTC, shravanipagilla commented
> Hey, @shravanipagilla I saw that you delivered PR #31 with the same suggestions that I commented on here. I greatly recommend you address them before going forward next time. It spares you from doing the same adjustments in two different PR and the Mentors from reviewing the same code. If you have any questions about the review don't hesitate to contact me! ☺️

Hej @annamourasobral thank you and sorry for that. with react my mind is not working properly... I made changes as per the comments some of not understand I will do it later ... thank you for your time:)

2022-10-17 17:25 UTC, annamourasobral approved these changes
Thank you for the updates!

2022-10-17 19:47 UTC, merged